name: Update PR
run-name: Updating PR ${{ github.ref }} with assignee and reviewer
on:
  # File is triggered by the main pipeline
  workflow_call:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto_update_pr:
    runs-on: self-hosted
    steps:
      - name: Add assignee to PR
        uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          configuration-path: '.github/settings/auto_update.yml'
