name: Start Unit Tests
run-name: Testing ${{ github.ref }} for ${{ github.actor }}
on:
  # File is triggered by the main pipeline
  workflow_call:

jobs:
  pytest:
    timeout-minutes: 30
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -e .[dev]
      - name: Run unit tests
        run: python3.11 -m pytest
      - name: Pytest Coverage Comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@v1.1.45
        with:
          pytest-xml-coverage-path: htmlcov/coverage.xml
          junitxml-path: htmlcov/pytest.xml
          title: PyTest Coverage
          badge-title: PyTest Coverage
          default-branch: ${{ github.ref }}
